USER_TYPE_ADMIN     = 2
USER_TYPE_ORGANIZER = 1
USER_TYPE_ATTENDEE  = 0

NO_SEAT             = 0
DEFAULT_SEAT        = 1
VIP_SEAT            = 2
PREMIUM_SEAT        = 3
OCCUPIED_SEAT       = 4

TICKET_STATE_EMPTY  = 0
TICKET_STATE_SOLD   = 1

PAYMENT_CREDIT_CARD = 0
PAYMENT_WALLET      = 1
